package com.smartlease.edge.report

import com.smartlease.edge.data.FindingType
import com.smartlease.edge.data.InspectionEntity
import com.smartlease.edge.data.SessionType
import com.smartlease.edge.data.Severity
import com.smartlease.edge.deduction.FindingDetail
import com.smartlease.edge.safety.SafetyGate
import com.smartlease.edge.ui.Property
import com.smartlease.edge.ui.Room

/**
 * Turns what the room-by-room capture flow holds in memory -- [Room]s, each with its
 * [com.smartlease.edge.ui.CapturedFrame]s and the defects the segmenter found in them -- into
 * the [InspectionEntity] rows the report pipeline has always consumed.
 *
 * This bridge exists because the capture flow and the report pipeline were built against
 * different stores. The walkthrough flow wrote every finding to Room (the database) as it went
 * and [ReportGenerator.buildReport] read them back out; the room-by-room flow keeps frames and
 * their defects in [com.smartlease.edge.ui.AppViewModel] and writes nothing. The result was
 * that the property flow could capture defects all day and never produce a report, a PDF, a
 * digest, or a countersignature -- the second half of the product was unreachable from the
 * first half. Rather than duplicating the report pipeline for a second data source, this maps
 * one shape onto the other.
 *
 * Two deliberate properties:
 *
 * 1. **Nothing is invented.** Every emitted row corresponds to exactly one detection the
 *    model actually produced, carrying that detection's own class, area estimate, and
 *    confidence. There is no synthesised "looks fine" row and no rounding of a low-confidence
 *    detection up into a finding.
 * 2. **`fromTrainedModel` is carried, not assumed.** It comes from the frame that produced the
 *    detection, so a heuristic-segmenter result stays labelled as one all the way into the
 *    PDF and the deduction sheet. Defaulting it to true here would quietly launder a
 *    heuristic guess into a model claim, which is the single easiest way for this project to
 *    end up overstating what it can do.
 */
object PropertyReportBuilder {

    /**
     * @param sessionId the id the report, its digest, and any countersignature are filed
     * under. Generated by the caller so the same id can be reused if the report is rebuilt.
     * @param timestampMs injectable purely so tests can assert on exact values; production
     * callers let each frame supply its own capture time.
     */
    fun findingsFor(
        property: Property,
        rooms: List<Room>,
        sessionId: String,
        sessionType: SessionType
    ): List<InspectionEntity> = rooms
        .filter { it.propertyId == property.id }
        .flatMap { room ->
            room.frames.flatMap { frame ->
                frame.defects.map { defect ->
                    // "Hall -- Sides: crack" reads as a location in a document, which is what
                    // a report is. The defect class stays a separate structured field so the
                    // rate card is never asked to parse prose back into a key.
                    val label = "${room.type} -- ${frame.surfaceType}: ${defect.label}"
                    val verdict = SafetyGate.evaluate(label)
                    InspectionEntity(
                        sessionId = sessionId,
                        timestampEpochMillis = frame.timestampMs,
                        findingType = FindingType.VISUAL_DEFECT,
                        label = label,
                        detailJson = FindingDetail.VisualDefect(
                            defectClass = defect.defectClass,
                            areaSqFt = defect.areaSqFtEstimate,
                            confidence = defect.confidence,
                            fromTrainedModel = frame.isTrainedModel
                        ).toJson(),
                        // A visual defect is NOTABLE; the hazard gate can raise it and
                        // nothing lowers it. Same rule the walkthrough flow applies, kept
                        // identical on purpose so two capture paths cannot disagree about how
                        // severe the same finding is.
                        severity = verdict.escalatedSeverity ?: Severity.NOTABLE,
                        sessionType = sessionType,
                        propertyLabel = property.name
                    )
                }
            }
        }

    /**
     * The deposit figure to price against, or null when the property carries none.
     *
     * [Property.depositAmount] is the raw text of an input field, so it may be blank, may
     * carry separators a user typed ("20,000", "Rs 20000"), and may be nonsense. Digits are
     * extracted rather than `toIntOrNull()` applied to the whole string, because dropping a
     * legible "20,000" to null would silently produce a report with no balance sheet at all.
     * A value with no digits stays null: no deposit is a real state, and inventing zero would
     * render as "you owe your entire deposit" on a report someone signs.
     */
    fun depositRupeesOrNull(property: Property): Int? {
        val digits = property.depositAmount.filter { it.isDigit() }
        if (digits.isEmpty()) return null
        return digits.toIntOrNull()
    }
}
