"""
Fit the tap classifier on Kotlin-portable features and export everything Android needs.

Writes app/src/main/assets/acoustic_tap_model.json containing:

  * the mel filterbank (40 x 257) and DCT-II basis (13 x 40) as plain matrices, so Kotlin
    multiplies instead of reconstructing them and cannot drift from the trainer;
  * the StandardScaler mean/scale and the logistic-regression coefficients, i.e. the model;
  * golden vectors -- a deterministic synthetic tap, its expected 36 features and expected
    probability -- so a Kotlin unit test can prove parity rather than assume it.

The golden signal is generated from a closed-form expression that both sides can produce
exactly, which keeps the test self-contained (no audio file in test resources) while still
exercising the whole chain: FFT, mel projection, log, DCT, moments, scaling, linear model.
"""

import glob
import json
import os
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

import android_features as af
from train_tap_classifier import CLASSES, segment_taps, wilson_interval

GOLDEN_LENGTH = 5512          # 0.25 s at 22050 Hz, matching the tap window
GOLDEN_FREQ = 1200.0
GOLDEN_DECAY = 900.0


def golden_signal(n=GOLDEN_LENGTH, sr=af.SAMPLE_RATE):
    """
    Deterministic stand-in for a tap: a decaying tone plus a fixed-phase overtone.

    Closed form on purpose -- Kotlin regenerates it from the same three constants, so the
    parity test needs no waveform fixture and still covers every DSP stage.
    """
    t = np.arange(n, dtype=np.float64)
    env = np.exp(-t / GOLDEN_DECAY)
    wave = np.sin(2.0 * np.pi * GOLDEN_FREQ * t / sr) + 0.5 * np.sin(
        2.0 * np.pi * 2.0 * GOLDEN_FREQ * t / sr
    )
    return (wave * env).astype(np.float64)


def load_taps(audio_root):
    clips, y, groups = [], [], []
    for label, cls in enumerate(CLASSES):
        for path in sorted(glob.glob(os.path.join(audio_root, cls, "*.*"))):
            for clip in segment_taps(path):
                clips.append(clip)
                y.append(label)
                groups.append(os.path.basename(path))
    return clips, np.array(y), np.array(groups)


def main():
    audio_root = "../data/audio"
    clips, y, groups = load_taps(audio_root)
    X = np.array([af.extract(c) for c in clips])
    print("Dataset: %d taps, %d recordings, %d features" % (len(X), len(set(groups)), X.shape[1]))

    # Honest score for the exact recipe being shipped.
    logo = LeaveOneGroupOut()
    ok = tot = 0
    for tr, te in logo.split(X, y, groups):
        if len(np.unique(y[tr])) < 2:
            continue
        m = make_pipeline(StandardScaler(),
                          LogisticRegression(max_iter=5000, C=0.5, class_weight="balanced"))
        m.fit(X[tr], y[tr])
        ok += int((m.predict(X[te]) == y[te]).sum())
        tot += len(te)
    lo, hi = wilson_interval(ok, tot)
    print("Grouped LOGO accuracy: %.1f%% (%d/%d), 95%% CI %.0f-%.0f%%"
          % (ok / tot * 100, ok, tot, lo * 100, hi * 100))

    # Final fit on everything.
    pipeline = make_pipeline(StandardScaler(),
                             LogisticRegression(max_iter=5000, C=0.5, class_weight="balanced"))
    pipeline.fit(X, y)
    scaler, clf = pipeline[0], pipeline[-1]

    gold = golden_signal()
    gold_feats = af.extract(gold)
    gold_prob = float(pipeline.predict_proba(gold_feats.reshape(1, -1))[0][1])

    payload = {
        "_comment": "Generated by ml/acoustic/export_for_android.py -- do not hand-edit.",
        "sampleRate": af.SAMPLE_RATE,
        "nFft": af.N_FFT,
        "hop": af.HOP,
        "nMels": af.N_MELS,
        "nMfcc": af.N_MFCC,
        "topDb": af.TOP_DB,
        "amin": af.AMIN,
        "featureCount": int(X.shape[1]),
        "classes": CLASSES,
        "positiveClass": CLASSES[1],
        "melFilterbank": af.mel_filterbank().astype(np.float32).ravel().tolist(),
        "dctMatrix": af.dct_matrix().astype(np.float32).ravel().tolist(),
        "scalerMean": scaler.mean_.astype(np.float32).tolist(),
        "scalerScale": scaler.scale_.astype(np.float32).tolist(),
        "coefficients": clf.coef_[0].astype(np.float32).tolist(),
        "intercept": float(clf.intercept_[0]),
        "groupedAccuracy": ok / tot,
        "groupedAccuracyCi95": [lo, hi],
        "trainedTaps": int(len(X)),
        "golden": {
            "length": GOLDEN_LENGTH,
            "freq": GOLDEN_FREQ,
            "decay": GOLDEN_DECAY,
            "features": gold_feats.astype(np.float32).tolist(),
            "hollowProbability": gold_prob,
        },
    }

    out = Path("../../app/src/main/assets/acoustic_tap_model.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload), encoding="utf-8")
    size_kb = out.stat().st_size / 1024
    print("\nWrote %s (%.0f KB)" % (out.resolve(), size_kb))
    print("  mel filterbank %dx%d, DCT %dx%d, %d coefficients"
          % (af.N_MELS, af.N_BINS, af.N_MFCC, af.N_MELS, len(payload["coefficients"])))
    print("  golden hollow probability: %.6f" % gold_prob)


if __name__ == "__main__":
    main()
